/**
 * Embedded assets for single-file executable builds.
 * This file is auto-generated by scripts/build.ts during compilation.
 * DO NOT EDIT MANUALLY.
 *
 * In development mode, assets are served from disk.
 * In compiled mode, assets are served from these embedded strings.
 */

// Placeholder - this file is regenerated during build
export const EMBEDDED_MIGRATIONS: { sql: string; tag: string }[] = [];
export const EMBEDDED_MAINTENANCE_MIGRATIONS: { sql: string; tag: string }[] = [];
export const EMBEDDED_INDEX_HTML = "";
export const EMBEDDED_STYLES_CSS = "";
export const EMBEDDED_APP_JS = "";

// PWA shell: the manifest makes the app installable, and the service worker is what
// receives Web Push while the app is closed.
export const EMBEDDED_SERVICE_WORKER = "";
export const EMBEDDED_MANIFEST = "";

// Icon assets (base64 encoded)
export const EMBEDDED_ICONS: { [key: string]: string } = {};

// Builtin skills (path -> content, binary files are base64 encoded)
export const EMBEDDED_BUILTIN_SKILLS: { [path: string]: { content: string; binary: boolean } } = {};

// Release notes for current version (parsed from CHANGELOG.md during build)
export const EMBEDDED_CHANGELOG = "";

// Flag to check if assets are embedded (set to true during build)
export const IS_COMPILED_BINARY = false;
